package finder_test

import (
	"testing"

	"github.com/actfuns/navpath/finder"
	"github.com/actfuns/navpath/grid"
)

// testScenarios are shared across all finder tests.
// The expected path data was generated by qiao/PathFinding.js (JS reference)
// and verified manually for each finder variant.
var testScenarios = []struct {
	name                     string
	startX, startY, endX, endY int
	matrix                   [][]int
}{
	{
		name:    "simple 2x2",
		startX:  0, startY: 0, endX: 1, endY: 1,
		matrix: [][]int{
			{0, 0},
			{1, 0},
		},
	},
	{
		name:    "5x6 maze",
		startX:  1, startY: 1, endX: 4, endY: 4,
		matrix: [][]int{
			{0, 0, 0, 0, 0},
			{1, 0, 1, 1, 0},
			{1, 0, 1, 0, 0},
			{0, 1, 0, 0, 0},
			{1, 0, 1, 1, 0},
			{0, 0, 1, 0, 0},
		},
	},
	{
		name:    "5x6 maze B",
		startX:  0, startY: 3, endX: 3, endY: 3,
		matrix: [][]int{
			{0, 0, 0, 0, 0},
			{0, 0, 1, 1, 0},
			{0, 0, 1, 0, 0},
			{0, 0, 1, 0, 0},
			{1, 0, 1, 1, 0},
			{0, 0, 0, 0, 0},
		},
	},
	{
		name:    "large open 20x20",
		startX:  4, startY: 4, endX: 19, endY: 19,
		matrix: func() [][]int {
			m := make([][]int, 20)
			for i := range m {
				m[i] = make([]int, 20)
			}
			return m
		}(),
	},
}

type finderExpected struct {
	newFinder func() finder.Finder
	paths     [][][2]int
}

// finderTests stores expected paths for each finder.
// Values from qiao/PathFinding.js (JS reference).
var finderTests = map[string]*finderExpected{
	"AStar": {
		newFinder: func() finder.Finder { return finder.NewAStarFinder(nil) },
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {5, 4}, {5, 5}, {6, 5}, {6, 6}, {6, 7}, {7, 7}, {7, 8}, {8, 8}, {9, 8}, {9, 9}, {10, 9}, {11, 9}, {12, 9}, {12, 10}, {12, 11}, {12, 12}, {12, 13}, {12, 14}, {13, 14}, {13, 15}, {14, 15}, {14, 16}, {14, 17}, {15, 17}, {16, 17}, {17, 17}, {18, 17}, {19, 17}, {19, 18}, {19, 19}},
		},
	},
	"BestFirst": {
		newFinder: func() finder.Finder { return finder.NewBestFirstFinder(nil) },
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {5, 4}, {6, 4}, {7, 4}, {8, 4}, {9, 4}, {10, 4}, {11, 4}, {12, 4}, {13, 4}, {14, 4}, {15, 4}, {16, 4}, {17, 4}, {18, 4}, {19, 4}, {19, 5}, {19, 6}, {19, 7}, {19, 8}, {19, 9}, {19, 10}, {19, 11}, {19, 12}, {19, 13}, {19, 14}, {19, 15}, {19, 16}, {19, 17}, {19, 18}, {19, 19}},
		},
	},
	"Dijkstra": {
		newFinder: func() finder.Finder { return finder.NewDijkstraFinder(nil) },
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {4, 5}, {4, 6}, {4, 7}, {4, 8}, {4, 9}, {4, 10}, {4, 11}, {4, 12}, {4, 13}, {4, 14}, {4, 15}, {4, 16}, {4, 17}, {4, 18}, {4, 19}, {5, 19}, {6, 19}, {7, 19}, {8, 19}, {9, 19}, {10, 19}, {11, 19}, {12, 19}, {13, 19}, {14, 19}, {15, 19}, {16, 19}, {17, 19}, {18, 19}, {19, 19}},
		},
	},
	"BreadthFirst": {
		newFinder: func() finder.Finder { return finder.NewBreadthFirstFinder(nil) },
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {5, 4}, {6, 4}, {7, 4}, {8, 4}, {9, 4}, {10, 4}, {11, 4}, {12, 4}, {13, 4}, {14, 4}, {15, 4}, {16, 4}, {17, 4}, {18, 4}, {19, 4}, {19, 5}, {19, 6}, {19, 7}, {19, 8}, {19, 9}, {19, 10}, {19, 11}, {19, 12}, {19, 13}, {19, 14}, {19, 15}, {19, 16}, {19, 17}, {19, 18}, {19, 19}},
		},
	},
	"BiAStar": {
		newFinder: func() finder.Finder { return finder.NewBiAStarFinder(nil) },
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {5, 4}, {5, 5}, {6, 5}, {6, 6}, {6, 7}, {7, 7}, {7, 8}, {8, 8}, {9, 8}, {9, 9}, {10, 9}, {11, 9}, {12, 9}, {13, 9}, {13, 10}, {13, 11}, {13, 12}, {13, 13}, {14, 13}, {14, 14}, {14, 15}, {15, 15}, {16, 15}, {17, 15}, {17, 16}, {18, 16}, {19, 16}, {19, 17}, {19, 18}, {19, 19}},
		},
	},
	"BiBestFirst": {
		newFinder: func() finder.Finder { return finder.NewBiBestFirstFinder(nil) },
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {5, 4}, {6, 4}, {7, 4}, {8, 4}, {9, 4}, {10, 4}, {11, 4}, {12, 4}, {13, 4}, {14, 4}, {15, 4}, {16, 4}, {17, 4}, {18, 4}, {19, 4}, {19, 5}, {19, 6}, {19, 7}, {19, 8}, {19, 9}, {19, 10}, {19, 11}, {19, 12}, {19, 13}, {19, 14}, {19, 15}, {19, 16}, {19, 17}, {19, 18}, {19, 19}},
		},
	},
	"BiDijkstra": {
		newFinder: func() finder.Finder { return finder.NewBiDijkstraFinder(nil) },
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {5, 4}, {6, 4}, {6, 5}, {7, 5}, {7, 6}, {7, 7}, {7, 8}, {7, 9}, {8, 9}, {8, 10}, {9, 10}, {9, 11}, {9, 12}, {10, 12}, {11, 12}, {11, 13}, {11, 14}, {12, 14}, {13, 14}, {14, 14}, {15, 14}, {16, 14}, {17, 14}, {17, 15}, {17, 16}, {18, 16}, {19, 16}, {19, 17}, {19, 18}, {19, 19}},
		},
	},
	"BiBreadthFirst": {
		newFinder: func() finder.Finder { return finder.NewBiBreadthFirstFinder(nil) },
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {5, 4}, {6, 4}, {7, 4}, {8, 4}, {9, 4}, {10, 4}, {11, 4}, {12, 4}, {13, 4}, {14, 4}, {15, 4}, {16, 4}, {17, 4}, {18, 4}, {19, 4}, {19, 5}, {19, 6}, {19, 7}, {19, 8}, {19, 9}, {19, 10}, {19, 11}, {19, 12}, {19, 13}, {19, 14}, {19, 15}, {19, 16}, {19, 17}, {19, 18}, {19, 19}},
		},
	},
	"IDAStar": {
		newFinder: func() finder.Finder { return finder.NewIDAStarFinder(nil) },
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {0, 2}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {3, 3}},
			{{4, 4}, {5, 4}, {6, 4}, {7, 4}, {8, 4}, {9, 4}, {10, 4}, {11, 4}, {12, 4}, {13, 4}, {14, 4}, {15, 4}, {16, 4}, {17, 4}, {18, 4}, {19, 4}, {19, 5}, {19, 6}, {19, 7}, {19, 8}, {19, 9}, {19, 10}, {19, 11}, {19, 12}, {19, 13}, {19, 14}, {19, 15}, {19, 16}, {19, 17}, {19, 18}, {19, 19}},
		},
	},
	"JPFNever": {
		newFinder: func() finder.Finder {
			return finder.JumpPointFinder(&finder.FinderOptions{DiagonalMovement: finder.DiagonalNever})
		},
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {4, 5}, {4, 6}, {4, 7}, {4, 8}, {4, 9}, {4, 10}, {4, 11}, {4, 12}, {4, 13}, {4, 14}, {4, 15}, {4, 16}, {4, 17}, {4, 18}, {4, 19}, {5, 19}, {6, 19}, {7, 19}, {8, 19}, {9, 19}, {10, 19}, {11, 19}, {12, 19}, {13, 19}, {14, 19}, {15, 19}, {16, 19}, {17, 19}, {18, 19}, {19, 19}},
		},
	},
	"JPFAlways": {
		newFinder: func() finder.Finder {
			return finder.JumpPointFinder(&finder.FinderOptions{DiagonalMovement: finder.DiagonalAlways})
		},
		paths: [][][2]int{
			{{0, 0}, {1, 1}},
			{{1, 1}, {1, 2}, {2, 3}, {3, 3}, {4, 4}},
			{{0, 3}, {1, 4}, {2, 5}, {3, 5}, {4, 4}, {3, 3}},
			{{4, 4}, {5, 5}, {6, 6}, {7, 7}, {8, 8}, {9, 9}, {10, 10}, {11, 11}, {12, 12}, {13, 13}, {14, 14}, {15, 15}, {16, 16}, {17, 17}, {18, 18}, {19, 19}},
		},
	},
	"JPFOnlyWhenNoObstacles": {
		newFinder: func() finder.Finder {
			return finder.JumpPointFinder(&finder.FinderOptions{DiagonalMovement: finder.DiagonalOnlyWhenNoObstacles})
		},
		paths: [][][2]int{
			{{0, 0}, {1, 0}, {1, 1}},
			{{1, 1}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 3}, {1, 4}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {4, 4}, {4, 3}, {3, 3}},
			{{4, 4}, {5, 5}, {6, 6}, {7, 7}, {8, 8}, {9, 9}, {10, 10}, {11, 11}, {12, 12}, {13, 13}, {14, 14}, {15, 15}, {16, 16}, {17, 17}, {18, 18}, {19, 19}},
		},
	},
	"JPFAtMostOne": {
		newFinder: func() finder.Finder {
			return finder.JumpPointFinder(&finder.FinderOptions{DiagonalMovement: finder.DiagonalIfAtMostOneObstacle})
		},
		paths: [][][2]int{
			{{0, 0}, {1, 1}},
			{{1, 1}, {2, 0}, {3, 0}, {4, 1}, {4, 2}, {4, 3}, {4, 4}},
			{{0, 3}, {1, 4}, {2, 5}, {3, 5}, {4, 4}, {3, 3}},
			{{4, 4}, {5, 5}, {6, 6}, {7, 7}, {8, 8}, {9, 9}, {10, 10}, {11, 11}, {12, 12}, {13, 13}, {14, 14}, {15, 15}, {16, 16}, {17, 17}, {18, 18}, {19, 19}},
		},
	},
}

// TestAllAgainstJS runs every finder on all 4 scenarios and compares
// against expected paths from qiao/PathFinding.js.
func TestAllAgainstJS(t *testing.T) {
	for name, ft := range finderTests {
		t.Run(name, func(t *testing.T) {
			for i, s := range testScenarios {
				g := grid.NewOrthogonalGrid(s.matrix)
				f := ft.newFinder()
				path := f.FindPath(s.startX, s.startY, s.endX, s.endY, g)
				if path == nil {
					t.Errorf("scenario %d: path not found", i+1)
					continue
				}
				if !pathEqual(path, ft.paths[i]) {
					t.Errorf("scenario %d:\n  got:  %v\n  want: %v", i+1, path, ft.paths[i])
				}
			}
		})
	}
}

// --- Constructor option tests ---

func TestAStarFinderWithOptions(t *testing.T) {
	opt := &finder.FinderOptions{
		AllowDiagonal:    true,
		DontCrossCorners: true,
		Weight:           2,
	}
	f := finder.NewAStarFinder(opt)
	if f.Weight != 2 {
		t.Errorf("expected Weight=2, got %v", f.Weight)
	}
	if f.DiagonalMovement != finder.DiagonalOnlyWhenNoObstacles {
		t.Errorf("expected DiagonalOnlyWhenNoObstacles, got %v", f.DiagonalMovement)
	}

	opt2 := &finder.FinderOptions{
		AllowDiagonal:    true,
		DontCrossCorners: false,
	}
	f2 := finder.NewAStarFinder(opt2)
	if f2.DiagonalMovement != finder.DiagonalIfAtMostOneObstacle {
		t.Errorf("expected DiagonalIfAtMostOneObstacle, got %v", f2.DiagonalMovement)
	}

	opt3 := &finder.FinderOptions{
		DiagonalMovement: finder.DiagonalAlways,
		Heuristic:        finder.Euclidean,
	}
	f3 := finder.NewAStarFinder(opt3)
	if f3.DiagonalMovement != finder.DiagonalAlways {
		t.Errorf("expected DiagonalAlways, got %v", f3.DiagonalMovement)
	}
}

func TestFinderUnreachablePath(t *testing.T) {
	// 1x3: start at (0,0), wall at (1,0), end at (2,0) unreachable
	g := grid.NewOrthogonalGrid([][]int{{0, 1, 0}})
	finders := []struct {
		name string
		f    finder.Finder
	}{
		{"AStar", finder.NewAStarFinder(nil)},
		{"Dijkstra", finder.NewDijkstraFinder(nil)},
		{"BreadthFirst", finder.NewBreadthFirstFinder(nil)},
		{"BestFirst", finder.NewBestFirstFinder(nil)},
		{"BiAStar", finder.NewBiAStarFinder(nil)},
		{"BiDijkstra", finder.NewBiDijkstraFinder(nil)},
		{"BiBreadthFirst", finder.NewBiBreadthFirstFinder(nil)},
		{"BiBestFirst", finder.NewBiBestFirstFinder(nil)},
		{"JPFNever", finder.JumpPointFinder(&finder.FinderOptions{DiagonalMovement: finder.DiagonalNever})},
	}
	for _, ft := range finders {
		t.Run(ft.name, func(t *testing.T) {
			path := ft.f.FindPath(0, 0, 2, 0, g)
			if path != nil {
				t.Errorf("expected nil for unreachable, got %v", path)
			}
		})
	}
}

func TestSingleCellGrid(t *testing.T) {
	finders := []finder.Finder{
		finder.NewAStarFinder(nil),
		finder.NewDijkstraFinder(nil),
		finder.NewBreadthFirstFinder(nil),
	}
	for i, f := range finders {
		g := grid.NewOrthogonalGrid([][]int{{0}})
		path := f.FindPath(0, 0, 0, 0, g)
		if path == nil {
			t.Errorf("finder %d (%T): expected path for single cell start==end", i, f)
		}
	}
}

func TestFinder1xNGrid(t *testing.T) {
	finders := []finder.Finder{
		finder.NewAStarFinder(nil),
		finder.NewDijkstraFinder(nil),
		finder.NewBreadthFirstFinder(nil),
	}
	// Create fresh grid per finder to avoid stale Node state
	for i, f := range finders {
		g := grid.NewOrthogonalGrid([][]int{{0, 0, 0}})
		path := f.FindPath(0, 0, 2, 0, g)
		if path == nil {
			t.Errorf("finder %d (%T): expected path on 1xN grid", i, f)
		}
	}
}

func TestFinderOptionsWeight(t *testing.T) {
	g := grid.NewOrthogonalGrid([][]int{
		{0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0},
	})
	// With very high weight, heuristic dominates → should still find a path
	f := finder.NewAStarFinder(&finder.FinderOptions{Weight: 100})
	path := f.FindPath(0, 0, 4, 1, g)
	if path == nil {
		t.Error("expected path even with high weight")
	}
	if path[0] != [2]int{0, 0} || path[len(path)-1] != [2]int{4, 1} {
		t.Error("wrong start/end")
	}
}

// --- Helper ---

func pathEqual(a, b [][2]int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
